### ISSUE TITLE
Bitwise AND with comparison failing in contracts

### ISSUE THREAD

**Issue by gustavung** [uuverifiers/tricera#8]
It is common to use bitmasking in C code, e.g. `a & 0xFF == 0xFF`. When using this pattern during inference of contracts, we get the following error "Other Error: method can only be applied to terms with a bit-vector sort".

Can be reproduced in the latest commit with the following input:
```
#define IS_MAX(a) ( (((a) & (0xFF)) == (0xFF) ) ? (1) : (0))

unsigned char b;
unsigned char flag;


extern void main();

/*@contract@*/
void test() {
    if (b == 255) flag = 1;
}

void main2()
{
    test();
}
extern int non_det_int();

void main()
{
  //Non-det assignment of global variables
  b = non_det_int();
  flag = non_det_int();

  //Initialization of logical old-variables
  int old_b;
  assume(old_b == b);

  //Function call that the harness function verifies
  main2();

  //The ensures-clauses translated into asserts
  assert(!((((!((old_b & 255) == 255) || 1) && (((old_b & 255) == 255) || 0) != 0) == 1) && !((flag != 0) == 1)));
}

```

**Comment by zafer-esen** [comment]
TriCera by default models `int` using mathematical integers. Bitwise operators require machine arithmetic, so an option except `math` should be passed using the following option:

`-arithMode:t	Integer semantics: math (default), ilp32, lp64, llp64`

Admittedly, there are currently shortcomings related to using machine integers too, mainly in the printing of solutions. 

I get the following contract with `-arithMode:ilp32`.

```
Inferred ACSL annotations
================================================================================
/* contracts for test */
/*@
  requires 2147483647 >= flag.\as[int] && 2147483647 >= b.\as[int];
  ensures b == \old(b) && (flag != 1 || (2147483647 >= \old(flag).\as[int] && 2147483647 >= \old(b).\as[int])) && (flag == 1 || flag.\as[int] >= 2147483648 || \old(flag).\as[int] >= 2147483648 || \old(b).\as[int] >= 2147483648 || 254 >= \old(b).\as[int] || \forall int v0; 256*v0 + \old(b).\as[int] != -1) && (flag == 1 || flag.\as[int] >= 2147483648 || \old(flag).\as[int] >= 2147483648 || 2147483647 >= \old(b).\as[int]) && (flag == 1 || 2147483647 >= \old(flag).\as[int]) && (2147483647 >= flag.\as[int] || \old(flag).\as[int] >= 2147483648);
*/
================================================================================
```

This requires some post-processing as we haven't really worked on supporting bit-vectors (how machine arithmetic is encoded under the hood) inside contracts until now, and a lot noisier due to ilp32 semantics.

Btw I got unsafe in the provided example, changing the line `if (b == 255) flag = 1;` to  `if ((b & 255) == 255)` resolved it.

**Comment by gustavung** [comment]
My mistake! By making the implementation and the top-level contract more consistent, Tricera was able to find a solution with `-arithMode:ilp32`. I see no further issue, and I will therefore close this thread.
